export enum ShortcutKey {
	SEARCH = "/",
	TOGGLE_COLOR_MODE = "`",
	CREATE_DECK = "a",
	FLASHCARD_FLIP_CARD = " ",
	NEXT_CARD = "arrowright",
	PREV_CARD = "arrowleft",
	LEARN_NEXT_QUESTION = " ",
	CHOICE_1 = "1",
	CHOICE_2 = "2",
	CHOICE_3 = "3",
	CHOICE_4 = "4",
	GET_A_HINT = "meta_shift_/",
	SKIP = "meta_shift_x",
}
